import { nanoid } from "nanoid";
import type { InsertUser, InsertProspect, InsertLead } from "@shared/schema";

// Demo users
export const demoUsers: InsertUser[] = [
  {
    username: "admin",
    password: "demo123", // This will be hashed when inserted
    name: "Marie Dubois",
    email: "marie@redweyne.fr",
    role: "operator"
  },
  {
    username: "alice.martin",
    password: "demo123",
    name: "Alice Martin",
    email: "alice.martin@redweyne.fr",
    role: "agent"
  },
  {
    username: "ben.leroy",
    password: "demo123",
    name: "Ben Leroy",
    email: "ben.leroy@redweyne.fr",
    role: "agent"
  }
];

// Demo prospects with realistic data
export const demoProspects: (Omit<InsertProspect, 'agentId' | 'score'> & { 
  prochaineAction?: Date;
  dernierContact?: Date;
})[] = [
  {
    id: nanoid(),
    nomComplet: "Jean Dupont",
    telephone: "06 12 34 56 78",
    email: "jean.dupont@email.fr",
    type: "Vendeur",
    ville: "Paris 15ème",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 450000,
    tauxHonoraires: 0.04,
    exclusif: true,
    motivation: "Déménagement professionnel",
    timeline: "2 mois",
    intention: "Vente rapide",
    source: "Site web",
    exactSource: "Google Ads - Estimation gratuite",
    consentement: true,
    statut: "Qualifié",
    adresse: "12 rue de la Convention, 75015 Paris",
    notes: "Client motivé, bien situé, exclusivité signée",
    agentOutcome: "in_negotiation",
    leadCost: 45,
    estimatedClosingDays: 60,
    prochaineAction: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Tomorrow
    dernierContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) // 2 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Marie Leroy",
    telephone: "06 98 76 54 32",
    email: "marie.leroy@email.fr",
    type: "Acheteur",
    ville: "Neuilly-sur-Seine",
    typeBien: "Maison",
    budget: 800000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Agrandissement familial",
    timeline: "6 mois",
    intention: "Recherche active",
    source: "Recommandation",
    exactSource: "Client référent - Jean Dupont",
    consentement: true,
    statut: "RDV fixé",
    adresse: "",
    notes: "Famille avec 2 enfants, recherche jardin",
    
    agentOutcome: "signed",
    leadCost: 0,
    estimatedClosingDays: 90,
    prochaineAction: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // In 3 days
    dernierContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) // Yesterday
  },
  {
    id: nanoid(),
    nomComplet: "Thomas Bernard",
    telephone: "06 45 67 89 12",
    email: "thomas.bernard@email.fr",
    type: "Vendeur",
    ville: "Boulogne-Billancourt",
    typeBien: "Studio",
    budget: 0,
    prixEstime: 280000,
    tauxHonoraires: 0.05,
    exclusif: false,
    motivation: "Investissement locatif",
    timeline: "1 mois",
    intention: "Vente urgente",
    source: "Facebook Ads",
    exactSource: "Facebook Ads - Estimation rapide studio",
    consentement: true,
    statut: "Mandate Pending",
    adresse: "8 avenue du Général Leclerc, 92100 Boulogne",
    notes: "Investisseur, plusieurs biens, urgent",
    
    agentOutcome: "in_negotiation",
    leadCost: 25,
    estimatedClosingDays: 30,
    prochaineAction: new Date(), // Today
    dernierContact: new Date(Date.now() - 3 * 60 * 60 * 1000) // 3 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Claire Moreau",
    telephone: "06 11 22 33 44",
    email: "claire.moreau@email.fr",
    type: "Acheteur",
    ville: "Vincennes",
    typeBien: "Appartement",
    budget: 550000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: true,
    motivation: "Premier achat",
    timeline: "3 mois",
    intention: "Recherche méthodique",
    source: "Le Bon Coin",
    exactSource: "Le Bon Coin - Annonce appartement Vincennes",
    consentement: true,
    statut: "Contacté",
    adresse: "",
    notes: "Primo-accédante, dossier solide, patient",
    
    leadCost: 12,
    estimatedClosingDays: 120,
    prochaineAction: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // Day after tomorrow
    dernierContact: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) // 5 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Philippe Durand",
    telephone: "06 55 44 33 22",
    email: "philippe.durand@email.fr",
    type: "Vendeur",
    ville: "Saint-Cloud",
    typeBien: "Maison",
    budget: 0,
    prixEstime: 1200000,
    tauxHonoraires: 0.035,
    exclusif: true,
    motivation: "Succession",
    timeline: "6 mois",
    intention: "Vente optimisée",
    source: "Porte à porte",
    exactSource: "Prospection secteur - Saint-Cloud centre",
    consentement: true,
    statut: "Mandat signé",
    adresse: "15 rue de la Paix, 92210 Saint-Cloud",
    notes: "Belle maison familiale, travaux à prévoir",
    
    agentOutcome: "signed",
    leadCost: 0,
    estimatedClosingDays: 180,
    prochaineAction: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // Next week
    dernierContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) // Yesterday
  },
  {
    id: nanoid(),
    nomComplet: "Isabelle Petit",
    telephone: "06 77 88 99 00",
    email: "isabelle.petit@email.fr",
    type: "Acheteur",
    ville: "Levallois-Perret",
    typeBien: "Appartement",
    budget: 420000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Rapprochement travail",
    timeline: "urgent",
    intention: "Achat rapide",
    source: "Site web",
    exactSource: "Google Search - Agence Levallois",
    consentement: true,
    statut: "Gagné",
    adresse: "",
    notes: "Achat finalisé - très satisfaite du service",
    
    agentOutcome: "signed",
    leadCost: 35,
    estimatedClosingDays: 45,
    dernierContact: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) // 10 days ago
  },
  // Additional prospects for comprehensive testing - distributed across 3 agents
  {
    id: nanoid(),
    nomComplet: "Antoine Rousseau",
    telephone: "06 12 13 14 15",
    email: "antoine.rousseau@email.fr",
    type: "Vendeur",
    ville: "Courbevoie",
    typeBien: "Duplex",
    budget: 0,
    prixEstime: 650000,
    tauxHonoraires: 0.04,
    exclusif: true,
    motivation: "Déménagement",
    timeline: "3 mois",
    intention: "Vente standard",
    source: "Recommandation",
    exactSource: "Recommandation - Ancien client Philippe",
    consentement: true,
    statut: "Nouveau",
    adresse: "25 boulevard de la Défense, 92400 Courbevoie",
    notes: "Appartement moderne avec vue sur la Défense",
    
    isHotLead: true,
    agentOutcome: "interested",
    leadCost: 0,
    estimatedClosingDays: 90,
    prochaineAction: new Date(), // Today
    dernierContact: new Date(Date.now() - 1 * 60 * 60 * 1000) // 1 hour ago
  },
  {
    id: nanoid(),
    nomComplet: "Camille Bonnet",
    telephone: "06 78 90 12 34",
    email: "camille.bonnet@email.fr",
    type: "Acheteur",
    ville: "Issy-les-Moulineaux",
    typeBien: "Appartement",
    budget: 380000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Premier achat",
    timeline: "moins de 3 mois",
    intention: "Achat urgent",
    source: "Google Ads",
    exactSource: "Google Ads - Première acquisition immobilière",
    consentement: true,
    statut: "RDV fixé",
    adresse: "",
    notes: "Jeune cadre, dossier solide, recherche transport proche",
    
    isHotLead: true,
    agentOutcome: "interested",
    leadCost: 42,
    estimatedClosingDays: 75,
    prochaineAction: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Tomorrow
    dernierContact: new Date(Date.now() - 4 * 60 * 60 * 1000) // 4 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Lucas Martin",
    telephone: "06 56 78 90 12",
    email: "lucas.martin@email.fr",
    type: "Vendeur",
    ville: "Meudon",
    typeBien: "Maison",
    budget: 0,
    prixEstime: 850000,
    tauxHonoraires: 0.035,
    exclusif: false,
    motivation: "Succession",
    timeline: "6 mois",
    intention: "Pas pressé",
    source: "Le Bon Coin",
    exactSource: "Le Bon Coin - Réponse annonce estimation",
    consentement: true,
    statut: "Contacté",
    adresse: "18 rue des Jardins, 92190 Meudon",
    notes: "Maison familiale, nécessite rafraîchissement",
    leadCost: 15,
    estimatedClosingDays: 180,
    prochaineAction: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // In 3 days
    dernierContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) // 2 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Élise Dubois",
    telephone: "06 34 56 78 90",
    email: "elise.dubois@email.fr",
    type: "Acheteur",
    ville: "Sèvres",
    typeBien: "Maison",
    budget: 720000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: true,
    motivation: "Agrandissement familial",
    timeline: "urgent",
    intention: "Recherche active",
    source: "Site web",
    exactSource: "Site web - Contact direct agence",
    consentement: true,
    statut: "Mandate Pending",
    adresse: "",
    notes: "Famille avec 3 enfants, cherche jardin et calme",
    leadCost: 28,
    estimatedClosingDays: 45,
    prochaineAction: new Date(), // Today
    dernierContact: new Date(Date.now() - 30 * 60 * 1000) // 30 minutes ago
  },
  {
    id: nanoid(),
    nomComplet: "Maxime Leroy",
    telephone: "06 90 12 34 56",
    email: "maxime.leroy@email.fr",
    type: "Vendeur",
    ville: "Puteaux",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 520000,
    tauxHonoraires: 0.04,
    exclusif: true,
    motivation: "Mutation professionnelle",
    timeline: "1 mois",
    intention: "Vente urgente",
    source: "Facebook Ads",
    exactSource: "Facebook Ads - Vente rapide Puteaux",
    consentement: true,
    statut: "Mandat signé",
    adresse: "12 avenue du Général de Gaulle, 92800 Puteaux",
    notes: "Proche métro, très bon état, mandat exclusif 3 mois",
    leadCost: 38,
    estimatedClosingDays: 60,
    prochaineAction: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // Day after tomorrow
    dernierContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) // Yesterday
  },
  {
    id: nanoid(),
    nomComplet: "Sarah Cohen",
    telephone: "06 23 45 67 89",
    email: "sarah.cohen@email.fr",
    type: "Acheteur",
    ville: "Rueil-Malmaison",
    typeBien: "Appartement",
    budget: 490000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Investissement locatif",
    timeline: "4 mois",
    intention: "Recherche méthodique",
    source: "Porte à porte",
    exactSource: "Prospection secteur - Rueil centre",
    consentement: true,
    statut: "Qualifié",
    adresse: "",
    notes: "Investisseuse expérimentée, recherche rentabilité 4%+",
    leadCost: 0,
    estimatedClosingDays: 120,
    prochaineAction: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000), // In 5 days
    dernierContact: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000) // 3 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Julien Blanc",
    telephone: "06 67 89 01 23",
    email: "julien.blanc@email.fr",
    type: "Vendeur",
    ville: "Asnières-sur-Seine",
    typeBien: "Studio",
    budget: 0,
    prixEstime: 220000,
    tauxHonoraires: 0.05,
    exclusif: false,
    motivation: "Optimisation patrimoniale",
    timeline: "2 mois",
    intention: "Vente conditionnelle",
    source: "Recommandation",
    exactSource: "Recommandation - Notaire Maître Dupont",
    consentement: true,
    statut: "En négociation",
    adresse: "5 rue Victor Hugo, 92600 Asnières",
    notes: "Studio refait à neuf, proche RER C",
    leadCost: 0,
    estimatedClosingDays: 75,
    prochaineAction: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Tomorrow
    dernierContact: new Date(Date.now() - 6 * 60 * 60 * 1000) // 6 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Amélie Moreau",
    telephone: "06 45 67 89 01",
    email: "amelie.moreau@email.fr",
    type: "Acheteur",
    ville: "Garches",
    typeBien: "Maison",
    budget: 950000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: true,
    motivation: "Résidence principale",
    timeline: "6 mois",
    intention: "Recherche sélective",
    source: "Site web",
    exactSource: "Google Search - Maison Garches",
    consentement: true,
    statut: "Perdu",
    adresse: "",
    notes: "A choisi une autre agence - prix trop élevé",
    leadCost: 52,
    estimatedClosingDays: 0,
    dernierContact: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000) // 15 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Nicolas Durand",
    telephone: "06 89 01 23 45",
    email: "nicolas.durand@email.fr",
    type: "Vendeur",
    ville: "Chatou",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 380000,
    tauxHonoraires: 0.04,
    exclusif: true,
    motivation: "Achat résidence secondaire",
    timeline: "3 mois",
    intention: "Vente conditionnelle",
    source: "Panneau vendu",
    exactSource: "Panneau A Vendre - Réponse téléphonique",
    consentement: true,
    statut: "Nouveau",
    adresse: "30 avenue de la République, 78400 Chatou",
    notes: "T3 avec balcon, parking inclus",
    leadCost: 0,
    estimatedClosingDays: 90,
    prochaineAction: new Date(), // Today
    dernierContact: new Date(Date.now() - 2 * 60 * 60 * 1000) // 2 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Céline Petit",
    telephone: "06 01 23 45 67",
    email: "celine.petit@email.fr",
    type: "Acheteur",
    ville: "Le Vésinet",
    typeBien: "Maison",
    budget: 1200000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Retour en France",
    timeline: "urgent",
    intention: "Achat rapide",
    source: "Recommandation",
    exactSource: "Recommandation - Collègue de travail",
    consentement: true,
    statut: "Gagné",
    adresse: "",
    notes: "Achat finalisé - maison 5 pièces avec jardin",
    leadCost: 0,
    estimatedClosingDays: 30,
    dernierContact: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) // 5 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Fabien Laurent",
    telephone: "06 76 54 32 10",
    email: "fabien.laurent@email.fr",
    type: "Vendeur",
    ville: "Montesson",
    typeBien: "Maison",
    budget: 0,
    prixEstime: 780000,
    tauxHonoraires: 0.035,
    exclusif: false,
    motivation: "Divorce",
    timeline: "4 mois",
    intention: "Vente nécessaire",
    source: "Google Ads",
    exactSource: "Google Ads - Vente maison Montesson",
    consentement: true,
    statut: "Contacté",
    adresse: "8 impasse des Tilleuls, 78360 Montesson",
    notes: "Situation délicate, vente nécessaire partage",
    leadCost: 48,
    estimatedClosingDays: 120,
    prochaineAction: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000), // In 4 days
    dernierContact: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) // 1 week ago
  },
  {
    id: nanoid(),
    nomComplet: "Stéphanie Roux",
    telephone: "06 32 10 98 76",
    email: "stephanie.roux@email.fr",
    type: "Acheteur",
    ville: "Croissy-sur-Seine",
    typeBien: "Appartement",
    budget: 420000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: true,
    motivation: "Rapprochement famille",
    timeline: "2 mois",
    intention: "Recherche ciblée",
    source: "Site web",
    exactSource: "Site web - Newsletter mensuelle",
    consentement: true,
    statut: "RDV fixé",
    adresse: "",
    notes: "Recherche T3 avec terrasse, budget ferme",
    leadCost: 18,
    estimatedClosingDays: 60,
    prochaineAction: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000), // Tomorrow
    dernierContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) // Yesterday
  },
  {
    id: nanoid(),
    nomComplet: "Vincent Garcia",
    telephone: "06 54 32 10 98",
    email: "vincent.garcia@email.fr",
    type: "Vendeur",
    ville: "Carrières-sur-Seine",
    typeBien: "Maison",
    budget: 0,
    prixEstime: 1100000,
    tauxHonoraires: 0.03,
    exclusif: true,
    motivation: "Retraite",
    timeline: "1 an",
    intention: "Pas pressé",
    source: "Porte à porte",
    exactSource: "Prospection - Carrières centre",
    consentement: true,
    statut: "Qualifié",
    adresse: "22 rue de la Seine, 78420 Carrières-sur-Seine",
    notes: "Belle propriété, vue sur Seine, travaux à prévoir",
    leadCost: 0,
    estimatedClosingDays: 300,
    prochaineAction: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // In 2 weeks
    dernierContact: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000) // 10 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Marina Silva",
    telephone: "06 98 76 54 32",
    email: "marina.silva@email.fr",
    type: "Acheteur",
    ville: "Houilles",
    typeBien: "Appartement",
    budget: 310000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Premier achat",
    timeline: "5 mois",
    intention: "Recherche prudente",
    source: "Facebook Ads",
    exactSource: "Facebook Ads - Primo accédant Houilles",
    consentement: true,
    statut: "Pas de réponse",
    adresse: "",
    notes: "Plus de 5 appels sans retour, abandonner",
    leadCost: 35,
    estimatedClosingDays: 0,
    dernierContact: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000) // 12 days ago
  },
  {
    id: nanoid(),
    nomComplet: "David Chen",
    telephone: "06 76 54 32 19",
    email: "david.chen@email.fr",
    type: "Vendeur",
    ville: "Sartrouville",
    typeBien: "Studio",
    budget: 0,
    prixEstime: 180000,
    tauxHonoraires: 0.05,
    exclusif: false,
    motivation: "Liquidation patrimoine",
    timeline: "2 mois",
    intention: "Vente rapide",
    source: "Le Bon Coin",
    exactSource: "Le Bon Coin - Réponse annonce vente rapide",
    consentement: true,
    statut: "En négociation",
    adresse: "14 boulevard Voltaire, 78500 Sartrouville",
    notes: "Studio rénové, prix négociable pour vente rapide",
    leadCost: 8,
    estimatedClosingDays: 45,
    prochaineAction: new Date(), // Today
    dernierContact: new Date(Date.now() - 3 * 60 * 60 * 1000) // 3 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Olivier Forestier",
    telephone: "06 11 22 33 44",
    email: "olivier.forestier@email.fr",
    type: "Acheteur",
    ville: "Versailles",
    typeBien: "Maison",
    budget: 1500000,
    prixEstime: 0,
    tauxHonoraires: 0.025,
    exclusif: true,
    motivation: "Résidence principale",
    timeline: "1 an",
    intention: "Recherche haut de gamme",
    source: "Recommandation",
    exactSource: "Recommandation - Banquier privé",
    consentement: true,
    statut: "Qualifié",
    adresse: "",
    notes: "Client fortuné, recherche propriété d'exception",
    leadCost: 0,
    estimatedClosingDays: 240,
    prochaineAction: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000), // In 10 days
    dernierContact: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000) // 5 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Émilie Rossignol",
    telephone: "06 87 65 43 21",
    email: "emilie.rossignol@email.fr",
    type: "Vendeur",
    ville: "Colombes",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 290000,
    tauxHonoraires: 0.045,
    exclusif: false,
    motivation: "Déménagement",
    timeline: "2 mois",
    intention: "Vente standard",
    source: "Panneau vendu",
    exactSource: "Appel suite panneau A Vendre",
    consentement: true,
    statut: "Contacté",
    adresse: "7 rue Lamartine, 92700 Colombes",
    notes: "T2 lumineux, proche métro ligne 13",
    leadCost: 0,
    estimatedClosingDays: 75,
    prochaineAction: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000), // In 6 days
    dernierContact: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000) // 8 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Benjamin Vidal",
    telephone: "06 55 44 33 22",
    email: "benjamin.vidal@email.fr",
    type: "Acheteur",
    ville: "Boulogne-Billancourt",
    typeBien: "Appartement",
    budget: 600000,
    prixEstime: 0,
    tauxHonoraires: 0.03,
    exclusif: false,
    motivation: "Investissement locatif",
    timeline: "3 mois",
    intention: "Recherche rentabilité",
    source: "Google Ads",
    exactSource: "Google Ads - Investissement locatif Boulogne",
    consentement: true,
    statut: "RDV fixé",
    adresse: "",
    notes: "Investisseur chevronné, recherche T3/T4",
    leadCost: 55,
    estimatedClosingDays: 90,
    prochaineAction: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // Day after tomorrow
    dernierContact: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) // 2 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Laëtitia Bernard",
    telephone: "06 33 44 55 66",
    email: "laetitia.bernard@email.fr",
    type: "Vendeur",
    ville: "Antony",
    typeBien: "Maison",
    budget: 0,
    prixEstime: 680000,
    tauxHonoraires: 0.035,
    exclusif: true,
    motivation: "Divorce",
    timeline: "urgent",
    intention: "Vente obligatoire",
    source: "Recommandation",
    exactSource: "Recommandation - Avocat divorce",
    consentement: true,
    statut: "Mandate Pending",
    adresse: "45 rue des Roses, 92160 Antony",
    notes: "Situation urgente, vente imposée par jugement",
    leadCost: 0,
    estimatedClosingDays: 60,
    prochaineAction: new Date(), // Today
    dernierContact: new Date(Date.now() - 45 * 60 * 1000) // 45 minutes ago
  }
];

// Demo leads for operator CRM
export const demoLeads: (Omit<InsertLead, 'ownerUserId' | 'assignedAgentId'> & { 
  id: string;
  prochaineAction?: Date;
  dernierContact?: Date;
  createdAt?: Date;
})[] = [
  {
    id: nanoid(),
    nomComplet: "Marc Dubois",
    telephone: "06 12 34 56 78",
    email: "marc.dubois@email.fr",
    type: "Vendeur",
    ville: "Paris 16ème",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 580000,
    motivation: "Mutation professionnelle",
    timeline: "2 mois",
    intention: "Vente rapide",
    source: "Facebook",
    exactSource: "Facebook Ads - Vente appartement Paris",
    consentement: true,
    statut: "New",
    adresse: "25 avenue Foch, 75016 Paris",
    notes: "Prospect très motivé, appartement bien situé",
    score: 85,
    isHotLead: true,
    cost: 42,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Sophie Lemaire",
    telephone: "06 98 76 54 32",
    email: "sophie.lemaire@email.fr",
    type: "Acheteur",
    ville: "Boulogne-Billancourt",
    typeBien: "Maison",
    budget: 750000,
    prixEstime: 0,
    motivation: "Agrandissement familial",
    timeline: "3 mois",
    intention: "Recherche active",
    source: "Google",
    exactSource: "Google Ads - Maison Boulogne",
    consentement: true,
    statut: "Contacted",
    notes: "Famille avec 2 enfants, recherche jardin",
    score: 70,
    isHotLead: false,
    cost: 35,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hours ago
    dernierContact: new Date(Date.now() - 30 * 60 * 1000), // 30 minutes ago
  },
  {
    id: nanoid(),
    nomComplet: "Pierre Martin",
    telephone: "06 45 67 89 12",
    email: "pierre.martin@email.fr",
    type: "Vendeur",
    ville: "Neuilly-sur-Seine",
    typeBien: "Studio",
    budget: 0,
    prixEstime: 320000,
    motivation: "Investissement",
    timeline: "1 mois",
    intention: "Vente urgente",
    source: "Direct",
    exactSource: "Appel direct agence",
    consentement: true,
    statut: "Follow-up",
    notes: "Studio rénové, proche métro",
    score: 60,
    isHotLead: false,
    cost: 0,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    prochaineAction: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow
    dernierContact: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Julie Moreau",
    telephone: "06 11 22 33 44",
    email: "julie.moreau@email.fr",
    type: "Acheteur",
    ville: "Levallois-Perret",
    typeBien: "Appartement",
    budget: 450000,
    prixEstime: 0,
    motivation: "Premier achat",
    timeline: "4 mois",
    intention: "Recherche méthodique",
    source: "Referral",
    exactSource: "Recommandation client Marc",
    consentement: true,
    statut: "Qualified",
    notes: "Primo-accédante, dossier solide",
    score: 75,
    isHotLead: true,
    cost: 0,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    prochaineAction: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000), // Day after tomorrow
    dernierContact: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
  },
  {
    id: nanoid(),
    nomComplet: "Antoine Rousseau",
    telephone: "06 55 44 33 22",
    email: "antoine.rousseau@email.fr",
    type: "Vendeur",
    ville: "Issy-les-Moulineaux",
    typeBien: "Duplex",
    budget: 0,
    prixEstime: 680000,
    motivation: "Déménagement",
    timeline: "5 mois",
    intention: "Vente standard",
    source: "Facebook",
    exactSource: "Facebook Ads - Duplex Issy",
    consentement: true,
    statut: "Booked",
    notes: "RDV fixé pour mardi prochain",
    score: 80,
    isHotLead: false,
    cost: 28,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
    prochaineAction: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000), // In 3 days
    dernierContact: new Date(Date.now() - 45 * 60 * 1000), // 45 minutes ago
  },
  {
    id: nanoid(),
    nomComplet: "Camille Bernard",
    telephone: "06 77 88 99 00",
    email: "camille.bernard@email.fr",
    type: "Acheteur",
    ville: "Saint-Cloud",
    typeBien: "Maison",
    budget: 950000,
    prixEstime: 0,
    motivation: "Résidence principale",
    timeline: "6 mois",
    intention: "Recherche sélective",
    source: "Google",
    exactSource: "Google Search - Maison Saint-Cloud",
    consentement: true,
    statut: "Sent to Agent",
    notes: "Dossier transmis à Alice Martin",
    score: 90,
    isHotLead: true,
    cost: 55,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    dernierContact: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Thomas Lefort",
    telephone: "06 33 44 55 66",
    email: "thomas.lefort@email.fr",
    type: "Vendeur",
    ville: "Puteaux",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 420000,
    motivation: "Achat résidence secondaire",
    timeline: "3 mois",
    intention: "Vente conditionnelle",
    source: "Direct",
    exactSource: "Panneau A Vendre - Appel direct",
    consentement: true,
    statut: "New",
    notes: "T3 avec balcon, proche La Défense",
    score: 65,
    isHotLead: false,
    cost: 0,
    createdAt: new Date(Date.now() - 30 * 60 * 1000), // 30 minutes ago
  },
  {
    id: nanoid(),
    nomComplet: "Élise Petit",
    telephone: "06 12 13 14 15",
    email: "elise.petit@email.fr",
    type: "Acheteur",
    ville: "Vincennes",
    typeBien: "Appartement",
    budget: 380000,
    prixEstime: 0,
    motivation: "Rapprochement travail",
    timeline: "urgent",
    intention: "Achat rapide",
    source: "Facebook",
    exactSource: "Facebook Ads - Appartement Vincennes",
    consentement: true,
    statut: "Sold",
    notes: "Vente finalisée, très satisfaite",
    score: 95,
    isHotLead: false,
    cost: 38,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    dernierContact: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
  },
  {
    id: nanoid(),
    nomComplet: "Lucas Garcia",
    telephone: "06 56 78 90 12",
    email: "lucas.garcia@email.fr",
    type: "Vendeur",
    ville: "Courbevoie",
    typeBien: "Studio",
    budget: 0,
    prixEstime: 250000,
    motivation: "Liquidation patrimoine",
    timeline: "2 mois",
    intention: "Vente rapide",
    source: "Google",
    exactSource: "Google Ads - Vente rapide studio",
    consentement: false,
    statut: "Bad Contact",
    notes: "Numéro incorrect, pas joignable",
    score: 0,
    isHotLead: false,
    badNumber: true,
    cost: 45,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Marine Dubois",
    telephone: "06 87 65 43 21",
    email: "marine.dubois@email.fr",
    type: "Acheteur",
    ville: "Garches",
    typeBien: "Maison",
    budget: 850000,
    prixEstime: 0,
    motivation: "Agrandissement familial",
    timeline: "4 mois",
    intention: "Recherche ciblée",
    source: "Referral",
    exactSource: "Recommandation banquier",
    consentement: true,
    statut: "Do Not Contact",
    notes: "A demandé à ne plus être contactée",
    score: 0,
    isHotLead: false,
    dnc: true,
    cost: 0,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    dernierContact: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000), // 4 days ago
  },
  {
    id: nanoid(),
    nomComplet: "Maxime Leroy",
    telephone: "06 90 12 34 56",
    email: "maxime.leroy@email.fr",
    type: "Vendeur",
    ville: "Rueil-Malmaison",
    typeBien: "Appartement",
    budget: 0,
    prixEstime: 520000,
    motivation: "Mutation professionnelle",
    timeline: "1 mois",
    intention: "Vente urgente",
    source: "Direct",
    exactSource: "Site web - Contact direct",
    consentement: true,
    statut: "Disqualified",
    notes: "Pas propriétaire, perte de temps",
    score: 10,
    isHotLead: false,
    cost: 0,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    dernierContact: new Date(Date.now() - 12 * 60 * 60 * 1000), // 12 hours ago
  },
  {
    id: nanoid(),
    nomComplet: "Stéphanie Martin",
    telephone: "06 23 45 67 89",
    email: "stephanie.martin@email.fr",
    type: "Acheteur",
    ville: "Meudon",
    typeBien: "Maison",
    budget: 720000,
    prixEstime: 0,
    motivation: "Résidence principale",
    timeline: "6 mois",
    intention: "Recherche patiente",
    source: "Google",
    exactSource: "Google Search - Maison Meudon",
    consentement: true,
    statut: "Refunded/Bad",
    notes: "Commission remboursée, problème dossier",
    score: 0,
    isHotLead: false,
    cost: 62,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 1 week ago
    dernierContact: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000), // 6 days ago
  }
];